# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Packages release (beta)

on:
  workflow_dispatch:

permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Setup git
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
      - name: Install packages
        run: |
          yarn config set disable-self-update-check true
          yarn config set ignore-engines true
          yarn config list
          yarn
      - name: Build all
        run: |
          yarn run build
      - name: Bump version
        run: |
          yarn version:beta --yes --no-push
      - name: publish to registry(github)
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "always-auth = true" >> .npmrc
          yarn publish:all:github
      - name: publish to registry(npmjs.com)
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_REGISTRY_TOKEN}}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth = true" >> .npmrc
          yarn publish:all --register=https://registry.npmjs.org/
      - name: push result
        run: |
          git push --force --tags
