# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Packages release (beta)

on:
  workflow_dispatch:

permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Setup git
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
      - run: yarn
      - name: Build all
        run: yarn run build:full
      - name: Bump version
        run: |
          yarn version:beta --yes
      - name: publish to registry(github)
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: yarn publish:all:github
      - name: publish to registry(npmjs.com)
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_REGISTRY_TOKEN}}
        run: yarn publish:all
